### ISSUE TITLE
Update screens layout and style

### ISSUE THREAD

**Issue by ntorionbearstudio** [BearStudio/start-ui-native#56]
## Description

We need to update the screens layout and style as designed by the designer team : https://www.figma.com/file/3197t2t2OyARyDIlRrwYXf/%F0%9F%9A%80-Start-UI-%5Bfigma%5D?node-id=363%3A1989

## Todo

- [x] Update Login Screen
- [x] Update Register Screen
- [x] Update Home Screen
- [x] Update Profile Screen
- [x] Create Update Profile screen
- [x] Create Change Password Screen
